stages:
  - maventry
  - androidtry
  - mavenDeploy

maven-build:   #this is a JOB
  stage: maventry
  tags:
    - springboot_tag  # this is LINK to the shell runner on the remote-server 
  script:
    - cd Backend
    - mvn package

android-build: #another job to build android
  image: inovex/gitlab-ci-android      # this is a directive to DOCKER
  stage: androidtry
  tags:
    - android_tag
  before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend
  #   - ./gradlewbuild
  # artifacts:
  #   paths:
  #     - Android_test/app/build/outputs/

android-test:  #another job to test android
  image: inovex/gitlab-ci-android
  stage: androidtry
  tags:
    - android_tag
  before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    - chmod +x ./Frontend/gradlew
  script:
    - cd Frontend
    # - .gradlew test
  

mavenDeploy:  #do make a stage with same name!
  stage: mavenDeploy
  tags:
   - springboot_tag
  script:
    - cd Backend
    - mvn package
    - sudo mv target/*.jar /target/KingOfTheRockServer-DEMO.jar
    - sudo systemctl stop system-web
    - sudo systemctl start system-web


